name: Svelte Continous Integration On GitHub

on:
  pull_request:
    brances: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: node env
        uses: actions/setup-node@v3
